default:
  # Use Red Hat UBI Python 3.12 for Red Hat environments
  # image: registry.access.redhat.com/ubi9/python-312:latest
  # Use public Python 3.12 for general use
  image: registry.access.redhat.com/ubi9/python-312:latest
  tags:
    - shared

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - build
  - test

pre-commit:
  stage: build
  before_script:
    - pip install uv
    - uv pip install -e ".[dev]"
  script:
    - pre-commit run --all-files
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

test:
  stage: test
  before_script:
    - pip install uv
    - uv pip install -e ".[dev]"
  script:
    - pytest tests/ -v
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
